import "../globals.css";
import { Layout } from "@/components/Layout";


/**
 * https://beta.nextjs.org/docs/guides/seo
 * https://beta.nextjs.org/docs/api-reference/metadata
 */

export const metadata = {
  title: "About Page",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head />
      <body>
        <Layout title="About Page Layout">{children}</Layout>
      </body>
    </html>
  );
}
