import "./globals.css";
import styles from "./layout.module.scss";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <nav className={styles.nav}>
          <Link href="/services">Services</Link>
          <Link href="/solutions">Solutions</Link>
        </nav>
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
