import "./globals.css";
import Link from "next/link";
import styles from "./layout.module.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head />
      <body>
        <nav className={styles.nav}>
          <Link className={styles.link} href="/">
            Home
          </Link>
          <Link className={styles.link} href="/dynamicparams-true">
            Dynamic Params true
          </Link>
          <Link className={styles.link} href="/dynamicparams-false">
            Dynamic Params false
          </Link>
        </nav>
        <main className={styles.main}>
          <div className={styles.box}>{children}</div>
        </main>
      </body>
    </html>
  );
}
